### ISSUE TITLE
Feedback about using toast notifications in Win32 apps

### ISSUE THREAD

**Issue by andrewleader** [Manomama7/KTU-AIS-Mark-Notifications#1]
Hi Martynas, my name is Andrew Leader, I work at Microsoft in the Windows Developer Platform team. We’re looking into how we can make toast notifications for Win32 apps easier to use.

I noticed your app utilizes notifications. Would you be able to share a bit about your experience implementing toast notifications in your app?

•	Summarize the general process you went through while implementing notifications (partially to help you recall all the steps you went through)
•	What was difficult?
•	What was easy/what did you enjoy?
•	Where did you spend more time than you felt you wanted to?
•	If you could have us change anything, what would you have us change?
•	What did you think of how toast activations (clicks) are handled? Is there a different way you would prefer to receive activations?

We’re seeking honest feedback, please do not be worried about insulting us or being too harsh, we want the truth so that we can make the lives of developers better 😊

I look forward to your response and appreciate your time! I’m also happy to schedule a call if you’d like to chat over video.

Thanks!
Andrew – PM on the Windows Developer Platform

**Comment by Martynas-S** [comment]
Hi Andrew!

Thanks for posting on my repository!
Unfortunately, I don't think I can help you out much right here. As you can see, I haven't worked on this project for quite a while and I honestly do not remember what were the problems setting up the toast notifications to work. As far as I remember, everything went mostly fine due to the availability of online resources which helped me out. 

Cheers!

**Comment by andrewleader** [comment]
Thanks for responding! That makes sense, I appreciate your reply, and feel free to reach out in the future if you use toasts again and have any problems!
